# Generated by Django 2.2.12 on 2022-03-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr', models.IntegerField()),
                ('Event', models.CharField(max_length=1024)),
                ('Date', models.DateField()),
                ('Note', models.CharField(max_length=256)),
                ('Img_url', models.CharField(max_length=2048)),
            ],
        ),
    ]
